name: First job
on: push

jobs:

  black:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - run: |
        pip install black==22.6.0
     - run: black --check .

  flake8:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4
      - run: |
          pip install flake8
      - run: flake8 --extend-ignore F401 .

  pytest:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - run: |
          pip install requests pandas pytest
      - run: pytest .
